version: "3"
services:
  web:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "!!test!!fablab!!"
      ACCEPT_EULA: "Y"